# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b1786014a22beb8ead9e81aef4d8e39864cf4fb62205f677ba80bc35686e2620c5abad849ae8d17245a8d808ef6879108a356729a9e743509c5d9a29379e5b9

test:
  secret_key_base: 2afa669ca35de3d9831f57dc628872bc3f045bbd8fe613ac74c0fa57e85281b44320940c16c05fd15cc29644d6322b06f75e529bc85b8962449e8af9b0eca16c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
